### ISSUE TITLE
맵 만들면서 안되고 모르는 것들 입니다...

### ISSUE THREAD

**Issue by Herecomessun** [yulcat/BeyondTheCity#10]
1. 계단 위로 올라가게 하기 위해서 설치하는 통과가능한 ground 위를 사람 캐릭터들이 지나갈 수 있는건가요...?
2. 물체를 떨어뜨려서 사람의 반응을 이끌어내야 하는데, 사람이 물체가 떨어진 소리에 반응을 안하네요ㅠ
3. 여자, 어린이, 남자 이렇게 세 종류의 사람을 쓰고 싶었는데 어떻게 바꾸는지를 모르겠어서 우선 다 여자로 해놓았습니다.
4. 쥐구멍을 설치했더니 계단 뒤에 숨어서 안보이는데 계단 앞으로 설치할 수 있나요?
- 제가 잘못 건드려서 상훈씨가 올린 맵이 revert 되었는데 취소를 못하겠네요ㅠ 
  다시 revert 시켰는데 이게 된건지는 잘 모르겠고....

**Comment by ShoyuVanilla** [comment]
1. 사람 캐릭터들이 지나갈 수 있고 동물 캐릭터들처럼 계단을 오르내릴 때 통과합니다.
2. 범위 바깥이라 그렇습니다.
3. 오브젝트 이름을 여자, 어린이, 남자로 설정해놓으시면 맞춰서 적용하겠습니다.
4. 쥐구멍 좌표의 z값을 -2정도로 바꿔보세요
