### ISSUE TITLE
맵 만들면서 모르는 점입니다. 

### ISSUE THREAD

**Issue by EunkyungJo** [yulcat/BeyondTheCity#11]
1. 쥐구멍 한 쌍을 각각 따로 컨트롤하고 싶은데 마우스 드래그로 옮겨지지 않네요. 쥐구멍 위치를 어떻게 조정해야 하나요? 

2.왼쪽 벽을 타고 고양이가 들어가게 하려고 하는데, 1층에는 문이 있어야 합니다.
1층부터 4층까지 벽을 만든 후에 1층에 문을 달아도 문이 작동하나요?
1. 개에 대한 사람의 반응이 Positive Attract인데도 개가 짖었을 때 사람이 반응을 안하네요.. AI의 작동을 위해서도 후처리가 필요한가요??

**Comment by ShoyuVanilla** [comment]
1. 쥐구멍 이름 왼쪽에 보시면 삼각형 모양이 있을 텐데 그것을 눌러서 하위 오브젝트 펼치면 따로 움직일 수 있습니다.
2. 문은 그냥 사람하고 닿으면 작동합니다. 위치는 무관합니다.
3. 개의 울음소리 범위가 좁아서 그렇습니다. 인스펙터에서 DogBehavior항목의 BarkPower 란에 숫자를 입력해서 범위를 조정할 수 있습니다. 현재는 AI가 소리가 나면 반응 여부에 관계없이 소리가 난 쪽으로 이동하게끔 해 놨는데 혹시 소리에도 각 동물을 본 것과 동일하게 행동하게끔 하는게 기획상 맞으면 변경하겠습니다.

**Comment by shhan826** [comment]
1. 그냥 한번 더 클릭해도 됩니다.
2. 넵 소리도 동물에 따라 다르게 해야할 것 같아요..
