### ISSUE TITLE
추가 문의사항입니다.

### ISSUE THREAD

**Issue by shhan826** [yulcat/BeyondTheCity#12]
1. 사람이 무서워/좋아/싫어 하는 반응들이 시야에서 사라지면 바로 없어지는데요, 이 반응 효과가 몇초간 지속되었으면 좋겠습니다.
2. 첫 시작 화면에서 카메라가 맵 전체 화면을 보여주고, 줌인해서 게임 플레이 화면으로 자연스럽게 넘어가는 게 있었으면 좋겠습니다. 그 사이 캐릭터들은 앞으로 이동하는 동작을 보여주고요! // 물론 죽거나 클리어했을때 피드백도 추가되었으면 좋겠지만요 ㅎㅎ
3. 캐릭터 기존에 보는 방향 바꾸는 방법 알려주세요!
- 맵 일부 수정했습니다. (이제 윗층의 사람 방향만 바꾸면 됩니다ㅋㅋ)

**Comment by ShoyuVanilla** [comment]
1. 반영하겠습니다.
2. 좋을 것 같네요. AI수정 후에 구현해볼게요.
3. Transform 인스펙터에서 Rotation값을 x = 0, y = 180, z = 0으로 입력하시면 됩니다.
