### ISSUE TITLE
문의사항입니다~

### ISSUE THREAD

**Issue by EunkyungJo** [yulcat/BeyondTheCity#13]
1. child의 쥐에 대한 반응이 negative repulse인데 child가 도망을 안가네요..
2. 계단 아랫쪽에(삼각형의 밑변에 붙어서) 쥐구멍을 놓고 싶었는데 계단 위에 놓으면 계단에 가려져 버리네요..  맨 앞으로 보내기(?)를 하려면 어떻게 해야 하나요? 
   아니면 계단에는 쥐구멍을 만들 수 없는건가요? 

수고가 많으십니다 ㅠㅠ
답변 감사합니다:)

**Comment by ShoyuVanilla** [comment]
1. 테스트 때는 제대로 작동했는데 한번 테스트해보고 알려드리겠습니다.
2. 쥐구멍의 z좌표를  -2 정도로 바꿔보세요
