### ISSUE TITLE
개발에 속도를 내주세요!

### ISSUE THREAD

**Issue by tjdwn1029** [yulcat/BeyondTheCity#5]
월요일 이후로 개발팀에서 소식을 듣지 못했습니다. 개발엔 제가 최대한 관여를 덜 할테니 속도를 내주시고 저를 계속 업데이트 시켜주세요. 개발이 늦어진다 싶으면 마감일을 지정하겠습니다.

**Comment by ShoyuVanilla** [comment]
다수의 컨트롤러로부터 인풋을 받아오는 부분에 대해 고민하고 있어서 지연되고 있습니다.
화요일까지는 마무리하겠습니다.

**Comment by tjdwn1029** [comment]
컨셉아트도 혹시 화요일까지 나올 수 있을까요?

**Comment by yulcat** [comment]
월요일까지 시험 과제 발표가 몰려있어서 신경을 못썼네요. 오늘내로 한장 이상은 뽑도록 하겠습니다.
