### ISSUE TITLE
push power, 물체 회전, 벽점프

### ISSUE THREAD

**Issue by tjdwn1029** [yulcat/BeyondTheCity#7]
1. push power 와 mass가 조절가능한데 push power를 늘려도 더 무거운 물체를 밀수있는건 아니더군요.
   (push power 1000으로 해도 mass가 100인 물체를 못 밉니다) 아직 적용이 안된 부분인가요?
2. 위로 높은 물체을 미는 경우 토크가 생겨서 물체가 누워버리는데 바닥이랑 물체랑 마찰계수를 조절하거나 물체가 회전 못하게 해야할것 같습니다. 전자가 더 설득력있는 방법일것 같습니다.
3. 고양이가 벽 뿐만 아니라 물체의 옆면에서도 벽점프 할 수 있게 해주세요.

**Comment by ShoyuVanilla** [comment]
3번 빼고는 해결 됐습니다.
