### ISSUE TITLE
맵 만들면서 모르겠는 점들 입니다.

### ISSUE THREAD

**Issue by shhan826** [yulcat/BeyondTheCity#9]
1. 천장을 만들고 싶은데 그냥 뜷고 넘어가버리네요
2. 보이지 않는? 벽이 존재합니다 (아무래도 피니시 하는 범위가 그런듯).. 보이게해주세요
3. 클리어포인트 만드는법 알려주세요
4. 저만그런건지 모르겠지만, 서로 등뒤에 못타요
5. 소리 어그로 고양이만 되요..설정 어떻게?
6. 쥐 울고 바로 구멍들어가기 누르면 구멍들어가져요 ㅋㅋ 쥐소리랑 구멍이랑 부딪혀서 그런가

...일단 만들긴했습니다. 플레이해보세요!!

**Comment by ShoyuVanilla** [comment]
1. 밑에서 못 뚫게 하려면 Ground 대신에 Wall을 붙이면 됩니다.
2. 우측만 막아놓았습니다.
3. 하이어라키에서 map 하위항목 보시면 "ClearBox"라는 오브젝트가 있습니다. 프리팹으로 빼 놓겠습니다.
4. 고양이와 개의 등은 올라탈 수 있고 쥐는 어색할 것 같아서 못 타게 해놓았습니다.
5. 시연버전에서는 고양이만 울음소리 범위를 넓게 해 놓았습니다. 인스펙터에서 "BarkPower"값을 조절해 범위를 변경할 수 있습니다.
6. 수정하겠습니다.
